In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

iris=load_iris()
X=iris.data
y=iris.target

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)
svm_model=SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)
y_pred=svm_model.predict(X_test)

accuracy=accuracy_score(y_test, y_pred)
recall=recall_score(y_test, y_pred, average='macro')
f1=f1_score(y_test, y_pred, average='macro')
conf_matrix=confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Confusion Matrix: \n{conf_matrix}")

Accuracy: 1.0000
Recall: 1.0000
F1 Score: 1.0000
Confusion Matrix: 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
